from AstronautBuilder import AstronautBuilder
commander = AstronautBuilder()
lunarModulePilot = AstronautBuilder()
commandModulePilot = AstronautBuilder()
commander.setName("Neil A. Armstrong")
commander.setAge(38)
commander.setAddress("1003 Woodland Dr.")
commander.setPhone("281-326-1951")
lunarModulePilot.setName("Edwin 'Buzz' E. Aldrin Jr.")
lunarModulePilot.setAge(39)
lunarModulePilot.setAddress("274 E Eau Gallie Blvd. 153")
lunarModulePilot.setPhone("904-814-3330")
commandModulePilot.setName("Michael Collins")
commandModulePilot.setAge(39)
commandModulePilot.setAddress("18503 Barbuda Ln.")
commandModulePilot.setPhone("202-358-0000")
print("Commander's Information:")
print(commander.getName())
print("Age", commander.getAge())
print(commander.getAddress())
print(commander.getPhone())
print("Lunar module pilot's information:")
print(lunarModulePilot.getName())
print("Age:", lunarModulePilot.getAge())
print(lunarModulePilot.getAddress())
print(lunarModulePilot.getPhone())
print("Command module pilot's information:")
print(commandModulePilot.getName())
print("Age:", commandModulePilot.getAge())
print(commandModulePilot.getAddress())
print(commandModulePilot.getPhone())
SystemExit